changelog:
  categories:
    - title: 🚀 Features
      labels:
        - release-scheduled
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: 🧰 Maintenance
      labels:
        - maintenance
        - bau
    - title: 📚 Documentation
      labels:
        - documentation
    - title: 🔗 Jira Issues
      labels:
        - jira
    - title: 🚧 In Progress
      labels:
        - in-progress
    - title: 🚩 Security
      labels:
        - security