changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot[bot]
  categories:
    - title: 🚀 Features
      labels:
        - release-scheduled
    - title: 🐛 Bug Fixes
      labels:
        - release-scheduled
    - title: 🚀 Breaking Changes
      labels:
        - release-scheduled
    - title: Other Changes
      labels:
        - "*" # Catch-all for pull requests that didn't match any of the previous categories