changelog:
  categories:
    - title: Breaking Changes 🛠
      labels:
        - release-scheduled
    - title: Exciting New Features 🎉
      labels:
        - release-scheduled
    - title: Other Changes
      labels:
        - "*"