changelog:
  categories:
    - title: 📝 Authors
      labels:
        - '*'
      include:
        authors:
          - '*'
    - title: Exciting New Features 🎉
      labels:
        - release-scheduled