name: Resuable Build Application

on:
  push:
    branches:
      - main

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Setup .NET Environment 
          uses: actions/setup-dotnet@v4
          with:
            dotnet-version: 8.0.x

        - name: Restore Application dependencies
          run: dotnet restore
        
        - name: Build Application Code
          run: dotnet build --no-restore

        - name : Publish Application code 
          run: dotnet publish -c Release -p PublishDir="resuable-artifact"

        - name: Upload Artifact
          uses: actions/upload-artifact@v4
          with:
            name: resuable-artifact
            path: ./resuable-artifact

    deploy:
        needs: build
        uses: ./.github/workflows/publish.yaml
        with:
            artifacts-name: resuable-artifact

            # Print results of the deploy job 
    print-status:
        needs: deploy
        runs-on: ubuntu-latest
        steps:
            - name: Print Deployment Status
              run: echo " Deployment status - ${{ needs.deploy.outputs.deployment-status }}"
