name: Resuable Deploy Application

# This workflow would be called by the build workflow to deploy the application
on: 
  workflow_call:
    inputs:
        artifacts-name:
            type: string
            required: true
            description: 'The name of the artifact to download'

        workflow_file:
            type: string
            required: true
            description: 'The file of the workflow to run'


jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Download Artifacts
              uses: actions/download-artifact@v4
              with:
                name: ${{ inputs.artifacts-name }}

            - name: List File Names
              run: ls

            - name: Deploy Application
              run: echo "Deploying Application to Production"